"""Shared schemas used by the forecasting agent, tools, rewards, and trainer."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import date, datetime
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


def parse_date(value: Any) -> date:
    """Parse common date representations into ``datetime.date``."""
    if isinstance(value, date):
        return value
    if isinstance(value, datetime):
        return value.date()
    if value is None:
        raise ValueError("date value cannot be None")
    text = str(value).strip()
    for fmt in ("%Y-%m-%d", "%Y/%m/%d", "%Y%m%d", "%Y-%m", "%Y/%m"):
        try:
            parsed = datetime.strptime(text, fmt)
            return parsed.date()
        except ValueError:
            continue
    raise ValueError(f"unsupported date format: {value!r}")


def date_to_str(value: date) -> str:
    return value.isoformat()


@dataclass(frozen=True)
class Event:
    """A structured temporal event tuple ``(t, s, r, o)``."""

    timestamp: date
    subject: str
    relation: str
    object: str
    source_id: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["timestamp"] = date_to_str(self.timestamp)
        return payload

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "Event":
        return cls(
            timestamp=parse_date(payload["timestamp"]),
            subject=str(payload["subject"]),
            relation=str(payload["relation"]),
            object=str(payload["object"]),
            source_id=str(payload.get("source_id", "")),
            metadata=dict(payload.get("metadata", {})),
        )

    def matches_entity(self, entity: str) -> bool:
        return entity == self.subject or entity == self.object

    def text(self) -> str:
        return f"{self.timestamp.isoformat()}: ({self.subject}, {self.relation}, {self.object})"


@dataclass(frozen=True)
class NewsArticle:
    """A timestamped text document used as unstructured forecasting evidence."""

    timestamp: date
    title: str
    text: str
    source_id: str = ""
    entities: Tuple[str, ...] = ()
    relations: Tuple[str, ...] = ()
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["timestamp"] = date_to_str(self.timestamp)
        payload["entities"] = list(self.entities)
        payload["relations"] = list(self.relations)
        return payload

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "NewsArticle":
        entities = payload.get("entities", ())
        relations = payload.get("relations", ())
        if isinstance(entities, str):
            entities = tuple(x.strip() for x in entities.split(";") if x.strip())
        if isinstance(relations, str):
            relations = tuple(x.strip() for x in relations.split(";") if x.strip())
        return cls(
            timestamp=parse_date(payload["timestamp"]),
            title=str(payload.get("title", "")),
            text=str(payload.get("text", "")),
            source_id=str(payload.get("source_id", "")),
            entities=tuple(entities),
            relations=tuple(relations),
            metadata=dict(payload.get("metadata", {})),
        )


@dataclass(frozen=True)
class ForecastQuery:
    """A query ``(s, o, ?, t)`` with optional ground truth for training/evaluation."""

    subject: str
    object: str
    timestamp: date
    query_id: str = ""
    candidate_relations: Tuple[str, ...] = ()
    ground_truth: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["timestamp"] = date_to_str(self.timestamp)
        payload["candidate_relations"] = list(self.candidate_relations)
        return payload

    @classmethod
    def from_event(cls, event: Event, candidates: Sequence[str]) -> "ForecastQuery":
        query_id = event.source_id or f"{event.subject}-{event.object}-{event.timestamp.isoformat()}"
        return cls(
            subject=event.subject,
            object=event.object,
            timestamp=event.timestamp,
            query_id=query_id,
            candidate_relations=tuple(candidates),
            ground_truth=event.relation,
        )

    def text(self) -> str:
        return f"q=({self.subject}, {self.object}, ?, {self.timestamp.isoformat()})"


@dataclass(frozen=True)
class Action:
    """A structured action generated by the policy."""

    name: str
    arguments: Dict[str, Any] = field(default_factory=dict)
    raw: str = ""

    def fingerprint(self) -> str:
        items = sorted((str(k), str(v)) for k, v in self.arguments.items())
        return f"{self.name}:{items}"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class Observation:
    """Environment response after executing an action."""

    tool_name: str
    ok: bool
    data: Dict[str, Any] = field(default_factory=dict)
    message: str = ""
    cost: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class FinalPrediction:
    """Final event prediction and its evidence summary."""

    label: str
    confidence: float = 0.0
    evidence: List[str] = field(default_factory=list)
    rationale: str = ""

    def is_valid(self) -> bool:
        return bool(self.label)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TrajectoryStep:
    """One ReAct step: action followed by observation."""

    action: Action
    observation: Observation

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action.to_dict(),
            "observation": self.observation.to_dict(),
        }


@dataclass
class Trajectory:
    """A complete tool-use trajectory for one forecasting query."""

    query: ForecastQuery
    steps: List[TrajectoryStep] = field(default_factory=list)
    final_prediction: Optional[FinalPrediction] = None
    terminated: bool = False
    termination_reason: str = ""
    generated_tokens: List[str] = field(default_factory=list)
    token_logprobs: List[float] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def total_cost(self) -> float:
        return sum(step.observation.cost for step in self.steps)

    @property
    def invalid_call_count(self) -> int:
        return sum(1 for step in self.steps if not step.observation.ok)

    @property
    def tool_call_count(self) -> int:
        return sum(1 for step in self.steps if step.action.name != "final_answer")

    def add_step(self, action: Action, observation: Observation) -> None:
        self.steps.append(TrajectoryStep(action=action, observation=observation))
        self.generated_tokens.extend(str(action.to_dict()).split())
        self.token_logprobs.extend([-0.1] * max(1, len(str(action.to_dict()).split())))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query.to_dict(),
            "steps": [step.to_dict() for step in self.steps],
            "final_prediction": None
            if self.final_prediction is None
            else self.final_prediction.to_dict(),
            "terminated": self.terminated,
            "termination_reason": self.termination_reason,
            "total_cost": self.total_cost,
            "metadata": self.metadata,
        }


@dataclass
class RewardBreakdown:
    """Detailed reward record for one trajectory."""

    outcome: float
    format_reward: float
    tool_reward: float
    retrieval_reward: float
    evidence_reward: float
    cost_penalty: float
    total: float
    details: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


def unique_relations(events: Iterable[Event]) -> Tuple[str, ...]:
    return tuple(sorted({event.relation for event in events}))
